.TH "PYTKEDITOR" "1" "May 2019" "pytkeditor 1.0.0a0" ""
.SH NAME
PyTkEditor \- Python IDE
.SH SYNOPSIS
.B pytkeditor [ \fIfiles\fR ]
.SH DESCRIPTION
Python3 IDE written with Tkinter for Linux.
.SH OPTIONS
.TP
.BR files
A space separated list of filenames.
.SH AUTHOR
PyTkEditor is developped by Juliette Monsel <j_4321@protonmail.com>
.SH BUGS
Please submit bugs on the Gitlab page of the project
\fBhttps://gitlab.com/j_4321/PyTkEditor/issues\fR
or send an email to <j_4321@protonmail.com>.
