.TH "TKEDITOR" "1" "May 2019" "tkeditor 1.0.0a0" ""
.SH NAME
TkEditor \- Python IDE
.SH SYNOPSIS
.B tkeditor [ \fIfiles\fR ]
.SH DESCRIPTION
Python3 IDE written with Tkinter for Linux.
.SH OPTIONS
.TP
.BR files
A space separated list of filenames.
.SH AUTHOR
TkEditor is developped by Juliette Monsel <j_4321@protonmail.com>
.SH BUGS
Please submit bugs on the Gitlab page of the project
\fBhttps://gitlab.com/j_4321/TkEditor/issues\fR
or send an email to <j_4321@protonmail.com>.
