#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys
from tkeditorlib.app import App
from tkeditorlib.constants import PIDFILE, OPENFILE_PATH
import os
import signal
from tkeditorlib.messagebox import showerror
import traceback

pid = str(os.getpid())

if os.path.isfile(PIDFILE):
    with open(PIDFILE) as fich:
        old_pid = fich.read().strip()
    if os.path.exists("/proc/%s" % old_pid):
        if len(sys.argv) > 1:
            with open(OPENFILE_PATH, 'w') as f:
                for path in sys.argv[1:]:
                    f.write(os.path.abspath(path) + '\n')
        os.kill(int(old_pid), signal.SIGUSR1)
        sys.exit()
    else:
        # it is an old pid file
        os.remove(PIDFILE)
open(PIDFILE, 'w').write(pid)


try:
    app = App(*sys.argv[1:])
    app.mainloop()
except Exception as e:
    msg = traceback.format_exc()
    print(msg)
    showerror("Error", "{}: {}".format(type(e), e), msg)
finally:
    try:
        os.unlink(PIDFILE)
    except Exception:
        pass
